import { type IEntitiesRepository } from '@kinotic-ai/persistence'
import { BaseLabelRepository } from './generated/BaseLabelRepository.js'

/**
 * Repository for interacting with Label entities
 * This class was generated by the Kinotic CLI
 */
export class LabelRepository extends BaseLabelRepository {

  constructor(entitiesRepository?: IEntitiesRepository) {
    super(false, entitiesRepository)
  }

}
