import { type IEntitiesRepository } from '@kinotic-ai/persistence'
import { BaseTodoRepository } from './generated/BaseTodoRepository.js'

/**
 * Repository for interacting with Todo entities
 * This class was generated by the Kinotic CLI
 */
export class TodoRepository extends BaseTodoRepository {

  constructor(entitiesRepository?: IEntitiesRepository) {
    super(false, entitiesRepository)
  }

}
