import { type IEntitiesRepository } from '@kinotic-ai/persistence'
import { BaseTodoListRepository } from './generated/BaseTodoListRepository.js'

/**
 * Repository for interacting with TodoList entities
 * This class was generated by the Kinotic CLI
 */
export class TodoListRepository extends BaseTodoListRepository {

  constructor(entitiesRepository?: IEntitiesRepository) {
    super(false, entitiesRepository)
  }

}
