import { Entity, AutoGeneratedId, NotNull, Text, Precision, PrecisionType, MultiTenancyType } from '@kinotic-ai/persistence'

/**
 * A cross-cutting tag that can be applied to any Todo (referenced by id in
 * Todo.labelIds). Used for filtering in the UI.
 */
@Entity(MultiTenancyType.NONE)
export class Label {
    @AutoGeneratedId
    id: string | null = null

    @NotNull
    @Text
    name: string = ''

    // hex colour for the label chip, e.g. '#f59e0b'
    color: string = '#f59e0b'

    @NotNull
    @Precision(PrecisionType.LONG)
    createdAt: number = 0

    @Precision(PrecisionType.LONG)
    updatedAt: number = 0
}
