import { Entity, AutoGeneratedId, NotNull, Text, Precision, PrecisionType, MultiTenancyType } from '@kinotic-ai/persistence'

@Entity(MultiTenancyType.NONE)
export class Todo {
    @AutoGeneratedId
    id: string | null = null

    @NotNull
    @Text
    title: string = ''

    @Text
    description: string = ''

    @NotNull
    completed: boolean = false

    // free-form priority label, e.g. 'low' | 'normal' | 'high' — kept as a keyword string
    priority: string = 'normal'

    // epoch millis; null until a due date is set
    @Precision(PrecisionType.LONG)
    dueDate: number | null = null

    // epoch millis, set on creation
    @NotNull
    @Precision(PrecisionType.LONG)
    createdAt: number = 0

    // epoch millis, updated on every edit
    @Precision(PrecisionType.LONG)
    updatedAt: number = 0
}
