import { Entity, AutoGeneratedId, NotNull, Text, Precision, PrecisionType, MultiTenancyType } from '@kinotic-ai/persistence'

/**
 * A named list (or board) that groups Todos. The UI shows these in a sidebar.
 */
@Entity(MultiTenancyType.NONE)
export class TodoList {
    @AutoGeneratedId
    id: string | null = null

    @NotNull
    @Text
    name: string = ''

    // hex colour for the list's swatch in the sidebar, e.g. '#4f46e5'
    color: string = '#64748b'

    // optional short description shown under the list header
    @Text
    description: string = ''

    // sort key for the sidebar; fractional so lists can be reordered without renumbering
    @Precision(PrecisionType.DOUBLE)
    position: number = 0

    @NotNull
    archived: boolean = false

    @NotNull
    @Precision(PrecisionType.LONG)
    createdAt: number = 0

    @Precision(PrecisionType.LONG)
    updatedAt: number = 0
}
