import { Entity, AutoGeneratedId, NotNull, Text, Precision, PrecisionType, MultiTenancyType } from '@kinotic-ai/persistence'

@Entity(MultiTenancyType.NONE)
export class Todo {
    @AutoGeneratedId
    id: string | null = null

    @NotNull
    @Text
    title: string = ''

    @Text
    description: string = ''

    @NotNull
    completed: boolean = false

    // free-form priority label, e.g. 'low' | 'normal' | 'high' — kept as a keyword string
    priority: string = 'normal'

    // id of the owning TodoList; '' means the default / inbox list
    listId: string = ''

    // ids of the Labels applied to this todo (keyword array, filterable)
    labelIds: string[] = []

    // sort key within a list; fractional so items can be reordered without renumbering
    @Precision(PrecisionType.DOUBLE)
    position: number = 0

    // epoch millis; null until a due date is set
    @Precision(PrecisionType.LONG)
    dueDate: number | null = null

    // epoch millis; set when `completed` flips to true, cleared when it flips back
    @Precision(PrecisionType.LONG)
    completedAt: number | null = null

    // epoch millis, set on creation
    @NotNull
    @Precision(PrecisionType.LONG)
    createdAt: number = 0

    // epoch millis, updated on every edit
    @Precision(PrecisionType.LONG)
    updatedAt: number = 0
}
